services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
  server:
    image: bloglist-backend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3003:3003
    container_name: bloglist-backend-dev
    environment:
      MONGODB_URL: mongodb://the_username:the_password@mongo:27017/the_database
      TEST_MONGODB_URL: mongodb://the_username:the_password@mongo:27017/test_the_database
      SECRET: /run/secrets/secret
      PORT: 3003
    command: ['npm', 'run', 'dev']

volumes:
  mongo_data:
    driver: local
secrets:
  secret:
    file: ./secret.txt